:pygments-style: tango
:source-highlighter: pygments
:toc:
:toclevels: 7
:sectnums:
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ../images/


=== Ansible Roles

Section Info Here

==== Ansible Role Overview

==== Using Roles


.DEMONSTRATION - Using a Role from Ansible Galaxy
====

. Change to correct working directory
+
[source,bash]
----
[student@workstation ~]$ cd Github/AAP_Webinar/Past/Roles/
----

. Install Role from Ansible Galaxy
+
[source,bash]
----
[student@workstation Roles]$ ansible-galaxy install -r roles/requirements.yml -p roles
Starting galaxy role install process
- downloading role 'ansiblize', owned by tmichett
- downloading role from https://github.com/tmichett/Ansiblize/archive/master.tar.gz
- extracting tmichett.ansiblize to /home/student/Github/AAP_Webinar/Past/Roles/roles/tmichett.ansiblize
- tmichett.ansiblize (master) was installed successfully
----

. Install Collections
+
[source,bash]
----
[student@workstation Roles]$ ansible-galaxy collection install -r collections/requirements.yml -p collections/
Starting galaxy collection install process
[WARNING]: The specified collections path
'/home/student/Github/AAP_Webinar/Past/Roles/collections' is not part of the
configured Ansible collections paths
'/home/student/.ansible/collections:/usr/share/ansible/collections'. The installed
collection won't be picked up in an Ansible run.
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/ansible-posix-1.3.0.tar.gz to /home/student/.ansible/tmp/ansible-local-37837_73lx2j8/tmpnadbl_rx/ansible-posix-1.3.0-xr73p6ye
Installing 'ansible.posix:1.3.0' to '/home/student/Github/AAP_Webinar/Past/Roles/collections/ansible_collections/ansible/posix'
ansible.posix:1.3.0 was installed successfully
----
+
[WARNING]
======
Because we are using a newer Ansible version, the regular modules are no longer available so we must install the Ansible Posix collection to use some of the modules in the role.
======

. Create/Modify Playbook with Correct Values and Providing Variables for the Role
+
[source,bash]
----
 create mode 100644 Workshop_Guide/redhat-theme.yml
[student@workstation Past]$ cd
[student@workstation ~]$ ls
---
- name: Playbook to Fully Setup and Configure a new User with a Role
  hosts: serverc
  vars: <1>
    ansible_user_name: travis
    ansible_user_password: redhat
  roles: <2>
    - tmichett.ansiblize
----
<1> Providing required variables for the role
<2> Providing the role being used

. Run the playbook with the *ansible-playbook* Command
+
[source,bash]
----
[student@workstation Roles]$ ansible-playbook Roles_Playbook_Demo.yml
----

. Test the results on *serverc*
.. SSH to ServerC
+
[source,bash]
----
[student@workstation Roles]$ ssh travis@serverc
----
.. Attempt to become root without password
+
[source,bash]
----
[travis@serverc ~]$ sudo -i
[root@serverc ~]#
----
====
