:pygments-style: tango
:source-highlighter: pygments
:icons: font
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]



=== Introduction to AAP 2.x Components

With Ansible 2.x, many new items have emerged. Ansible can now leverage execution environments which contain Ansible collections, different versions of Ansible, and the correct python versions and modules needed to execute a playbook. Ansible Execution Environments (EEs) allow developers and administrators more flexibility be leveraging a containerized Ansible environment. The use of Ansible EEs from a control node or developer workstation will work exactly the same with Ansible Controller (formerly known as Ansible Tower). Ansible Controller allows Ansible EEs to be assigned to projects, inventories, job templates, and more.

Ansible Private Automation Hub (Automation Hub) allows a self-hosted Ansible Galaxy. The local installation of Ansible Galaxy not only allows collections to be published privately within an organization, but it also provides a container registry for publishing custom Ansible EEs.


==== Ansible Content Navigator


.Source Description
[source,yaml]
----
---
ansible-navigator:
  execution-environment: <1>
    enabled: true
    environment-variables:
      set:
        ANSIBLE_CONFIG: ansible.cfg <2>
    image: hub.lab.example.com/ee-29-rhel8:latest <3>
  logging:
    level: critical
  mode: stdout <3>

----
<1> Configures Ansible Navigator to use an Execution Environment (EE)
<2> Specifies where Ansible Navigator and the Ansible EE will receive Ansible configuration settings
<3> Specifies Ansible EE to use for Ansible Navigator
<4> Specified Mode, in this case, we are using *STDOUT* so that the output will look like it does with the *_ansible-playbook_* command.


==== Ansible Execution Environments


.DEMO - *Using Ansible Content Navigator and the Ansible 2.9 Execution Environment*
====

====
